const countryCodeMap: Record<string, string> = {
  'united-states': 'us',
  'united-kingdom': 'gb',
  'spain': 'es',
  'france': 'fr',
  'germany': 'de',
  'italy': 'it',
  'netherlands': 'nl',
  'portugal': 'pt',
  'greece': 'gr',
  'switzerland': 'ch',
  'austria': 'at',
  'belgium': 'be',
  'denmark': 'dk',
  'finland': 'fi',
  'ireland': 'ie',
  'norway': 'no',
  'sweden': 'se',
  'canada': 'ca',
  'mexico': 'mx',
  'brazil': 'br',
  'argentina': 'ar',
  'chile': 'cl',
  'colombia': 'co',
  'peru': 'pe',
  'venezuela': 've',
  'japan': 'jp',
  'china': 'cn',
  'south-korea': 'kr',
  'india': 'in',
  'australia': 'au',
  'new-zealand': 'nz',
  'singapore': 'sg',
  'thailand': 'th',
  'malaysia': 'my',
  'russia': 'ru',
  'turkey': 'tr',
  'israel': 'il',
  'south-africa': 'za',
  'egypt': 'eg',
  'morocco': 'ma'
};

export function getCountryCode(slug: string): string {
  return countryCodeMap[slug.toLowerCase()] || 'un';
}